import React, { useContext, useEffect, useState } from 'react';
import { AuthContext } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import API_URL from '../config/api';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { motion, AnimatePresence } from 'framer-motion';
import { Leaf, Award, Footprints, Star, TrendingUp, Cpu, FileText, Zap, XCircle, Gift } from 'lucide-react';

const aiSuggestionsLog = [
  "Switching to 100% LED lighting today will save approx 40kg of CO₂ monthly based on your usage.",
  "Consider eating plant-based 3 days a week to slash your dietary footprint by 45%.",
  "Replacing weekend driving with cycling avoids 12kg CO₂ per trip. Start this weekend!",
  "Unplugging phantom electronics at night will decrease your annual footprint by 3%."
];

const Dashboard = () => {
  const { user, loading } = useContext(AuthContext);
  const navigate = useNavigate();
  const [history, setHistory] = useState([]);
  const [dataLoading, setDataLoading] = useState(true);
  const [reportModal, setReportModal] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState("");

  useEffect(() => {
    if (!loading && !user) navigate('/login');
  }, [user, loading, navigate]);

  useEffect(() => {
    if (user?.id || user?._id) {
      const fetchHistory = async () => {
        try {
          const token = localStorage.getItem('token');
          const res = await axios.get(`${API_URL}/api/footprint/history`, {
             headers: { Authorization: `Bearer ${token}` }
          });
          const formatted = res.data.data.map(log => ({
            name: new Date(log.createdAt).toLocaleDateString(),
            CO2: log.total_kg_co2
          }));
          setHistory(formatted);
          setAiSuggestion(aiSuggestionsLog[Math.floor(Math.random() * aiSuggestionsLog.length)]);
        } catch (err) {
          console.error('Failed to fetch history', err);
        } finally {
          setDataLoading(false);
        }
      };
      fetchHistory();
    } else {
        setDataLoading(false);
    }
  }, [user?.id, user?._id]);

  if (loading || dataLoading) return <div className="min-h-screen bg-[var(--color-earth-sand)] dark:bg-gray-900 flex justify-center items-center"><div className="w-16 h-16 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin"></div></div>;
  if (!user) return null;

  // Gamification Math (Secure against undefined/null)
  const safeXp = user.xp || 0;
  const level = Math.floor(safeXp / 100) + 1;
  const xpInCurrentLevel = safeXp % 100;
  const progressPercent = xpInCurrentLevel;

  // Predictive Graph Logic
  const latestCO2 = history.length > 0 ? history[history.length - 1].CO2 : 0;
  const predictiveData = history.length > 0 ? [
      { year: '2025', 'Current Trajectory': latestCO2, 'Sustainable Goal': latestCO2 },
      { year: '2027', 'Current Trajectory': latestCO2 * 1.05, 'Sustainable Goal': latestCO2 * 0.8 },
      { year: '2030', 'Current Trajectory': latestCO2 * 1.15, 'Sustainable Goal': latestCO2 * 0.45 },
  ] : [];

  return (
    <div className="bg-[var(--color-earth-sand)] dark:bg-[var(--color-deep-ocean)] min-h-screen pb-20 pt-24 transition-colors duration-700 font-sans">
      {/* Smart Report Modal */}
      <AnimatePresence>
        {reportModal && (
          <motion.div 
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex justify-center items-center bg-black/60 backdrop-blur-sm p-4"
          >
            <motion.div 
              initial={{ scale: 0.9, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.9, opacity: 0 }}
              className="bg-white dark:bg-gray-900 w-full max-w-2xl rounded-[2.5rem] p-10 shadow-2xl relative border border-emerald-500/20"
            >
              <button onClick={() => setReportModal(false)} className="absolute top-6 right-6 text-gray-400 hover:text-red-500 transition-colors">
                 <XCircle size={32} />
              </button>
              
              <div className="flex items-center gap-4 mb-8 border-b dark:border-gray-800 pb-6">
                 <div className="p-4 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 rounded-2xl"><FileText size={32}/></div>
                 <div>
                    <h2 className="text-3xl font-black text-gray-800 dark:text-white font-heading">Smart Climate Report</h2>
                    <p className="text-sm font-bold text-gray-500 uppercase tracking-widest">Generated by Earth AI</p>
                 </div>
              </div>

              <div className="space-y-6">
                 <div className="flex justify-between items-center bg-gray-50 dark:bg-gray-800 p-6 rounded-2xl border dark:border-gray-700">
                    <span className="font-bold text-gray-600 dark:text-gray-300">Total Logged Footprint</span>
                    <span className="text-3xl font-black font-mono text-gray-800 dark:text-white">{latestCO2.toFixed(1)} kg</span>
                 </div>
                 <div className="flex justify-between items-center bg-gray-50 dark:bg-gray-800 p-6 rounded-2xl border dark:border-gray-700">
                    <span className="font-bold text-gray-600 dark:text-gray-300">National Average Comparison</span>
                    <span className="text-xl font-black text-emerald-600">You are 14% lower</span>
                 </div>
                 <div className="flex justify-between items-center bg-gray-50 dark:bg-gray-800 p-6 rounded-2xl border dark:border-gray-700">
                    <span className="font-bold text-gray-600 dark:text-gray-300">Suggested Action Protocol</span>
                    <span className="text-sm font-bold text-blue-500">Commence Zero-Waste Policy</span>
                 </div>
              </div>

              <button onClick={() => setReportModal(false)} className="mt-8 w-full bg-black dark:bg-emerald-500 text-white py-4 rounded-xl font-black uppercase tracking-widest hover:bg-[var(--color-terracotta)] dark:hover:bg-emerald-400 transition-all shadow-xl">
                 Acknowledge & Close
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="bg-[var(--color-forest-canopy)] dark:bg-black py-20 px-4 mt-[-60px] border-b border-white/5 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-emerald-500/10 rounded-full filter blur-[100px]"></div>
        <div className="container mx-auto relative z-10">
          <motion.div 
            initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }}
            className="bg-white/10 backdrop-blur-xl p-10 md:p-14 rounded-[3rem] text-white max-w-5xl shadow-2xl relative overflow-hidden border border-white/10"
          >
            <div className="absolute -right-10 -top-20 opacity-5">
              <Leaf size={400} />
            </div>
            
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-8 relative z-10">
                <div>
                    <h1 className="text-5xl md:text-6xl font-heading font-black mb-2">Welcome, {user.name}</h1>
                    <p className="text-emerald-300 font-bold tracking-widest uppercase text-sm mb-8">Earth Defender Level {level}</p>
                    <div className="flex flex-wrap gap-4">
                        <button onClick={() => setReportModal(true)} className="flex items-center gap-3 bg-white text-[var(--color-forest-canopy)] px-6 py-3 rounded-full font-black text-sm uppercase tracking-widest hover:bg-[var(--color-terracotta)] hover:text-white transition-all shadow-lg hover:shadow-2xl">
                            <FileText size={18} /> Smart Report
                        </button>
                        <button onClick={() => navigate('/rewards')} className="flex items-center gap-3 bg-gradient-to-r from-emerald-500 to-emerald-400 text-white px-6 py-3 rounded-full font-black text-sm uppercase tracking-widest hover:text-white transition-all shadow-lg hover:shadow-2xl hover:-translate-y-1">
                            <Gift size={18} /> Spend XP
                        </button>
                    </div>
                </div>

                <div className="bg-black/40 backdrop-blur-md p-8 rounded-3xl border border-white/10 shadow-inner min-w-[300px]">
                  <div className="flex justify-between items-end mb-4">
                    <div className="flex items-center gap-3">
                      <Star className="text-yellow-400 w-8 h-8" fill="currentColor" />
                      <span className="font-black text-3xl">{user.xp || 0} XP</span>
                    </div>
                    <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">{100 - xpInCurrentLevel} to Lvl {level + 1}</span>
                  </div>
                  <div className="w-full bg-black/60 rounded-full h-4 overflow-hidden border border-white/5">
                    <div className="bg-gradient-to-r from-yellow-400 via-emerald-400 to-emerald-500 h-4 rounded-full shadow-[0_0_20px_rgba(52,211,153,0.8)] transition-all duration-1000" style={{ width: `${progressPercent}%` }}></div>
                  </div>
                </div>
            </div>
          </motion.div>
        </div>
      </div>

      <div className="container mx-auto px-6 -mt-10 relative z-20">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          <motion.div 
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1, duration: 0.5 }}
            className="bg-white dark:bg-gray-800 p-8 rounded-3xl shadow-xl border border-gray-100 dark:border-gray-700 flex items-center gap-6 hover:shadow-2xl hover:shadow-emerald-500/20 hover:-translate-y-2 transition-all duration-300 cursor-pointer"
          >
            <div className="bg-emerald-50 dark:bg-emerald-900/30 p-5 rounded-2xl text-emerald-600 dark:text-emerald-400"><Footprints size={32} /></div>
            <div>
              <p className="text-xs text-gray-400 uppercase tracking-[0.2em] font-bold mb-1">Latest Impact</p>
              <p className="text-3xl font-black font-mono text-gray-800 dark:text-white">
                {latestCO2.toFixed(1)} <span className="text-lg text-gray-400 font-sans">kg</span>
              </p>
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.5 }}
            className="bg-white dark:bg-gray-800 p-8 rounded-3xl shadow-xl border border-gray-100 dark:border-gray-700 flex items-center gap-6 hover:shadow-2xl hover:shadow-terracotta-500/20 hover:-translate-y-2 transition-all duration-300 cursor-pointer"
          >
            <div className="bg-[var(--color-terracotta)]/10 p-5 rounded-2xl text-[var(--color-terracotta)]"><TrendingUp size={32} /></div>
            <div>
              <p className="text-xs text-gray-400 uppercase tracking-[0.2em] font-bold mb-1">Calculations</p>
              <p className="text-3xl font-black font-mono text-gray-800 dark:text-white">{history.length}</p>
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="bg-white dark:bg-gray-800 p-8 rounded-3xl shadow-xl border border-gray-100 dark:border-gray-700 flex items-center gap-6 hover:shadow-2xl hover:shadow-blue-500/20 hover:-translate-y-2 transition-all duration-300 cursor-pointer"
          >
            <div className="bg-blue-50 dark:bg-blue-900/30 p-5 rounded-2xl text-blue-500 dark:text-blue-400"><Award size={32} /></div>
            <div>
              <p className="text-xs text-gray-400 uppercase tracking-[0.2em] font-bold mb-1">Global Status</p>
              <p className="text-2xl font-black text-gray-800 dark:text-white capitalize">{user.role}</p>
            </div>
          </motion.div>
        </div>

        {/* How to Earn XP Quick Guide */}
        <div className="bg-white dark:bg-gray-800 p-8 rounded-3xl shadow-xl border border-gray-100 dark:border-gray-700 mb-12">
            <h3 className="text-sm font-bold tracking-widest uppercase text-emerald-500 mb-6 flex items-center gap-2"><Star size={16}/> How to collect Reward XP</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="flex items-start gap-4 p-4 rounded-2xl bg-gray-50 dark:bg-gray-900 border border-transparent hover:border-emerald-500/30 transition-colors">
                    <div className="bg-white dark:bg-gray-800 p-3 rounded-xl shadow-sm"><Footprints className="text-emerald-500" size={24}/></div>
                    <div>
                        <h4 className="font-bold text-gray-900 dark:text-gray-100 mb-1">Log Daily Footprints</h4>
                        <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">Head to the <a href="/calculator" className="text-emerald-500 hover:underline">Calculator</a> and save your daily estimated footprint results to your history to earn standard XP points.</p>
                    </div>
                </div>
                <div className="flex items-start gap-4 p-4 rounded-2xl bg-gray-50 dark:bg-gray-900 border border-transparent hover:border-emerald-500/30 transition-colors">
                    <div className="bg-white dark:bg-gray-800 p-3 rounded-xl shadow-sm"><Leaf className="text-emerald-500" size={24}/></div>
                    <div>
                        <h4 className="font-bold text-gray-900 dark:text-gray-100 mb-1">Climate Challenges</h4>
                        <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">Coming soon: complete 7-day sustainable living challenges in the Eco-Habit tracker to earn massive XP multipliers.</p>
                    </div>
                </div>
            </div>
        </div>

        {/* AI Suggestion Module */}
        <div className="bg-gradient-to-r from-[var(--color-forest-canopy)] to-[var(--color-deep-ocean)] dark:from-gray-800 dark:to-black p-8 rounded-3xl shadow-2xl mb-12 border border-emerald-500/20 flex flex-col md:flex-row items-center gap-6 relative overflow-hidden">
             <div className="p-4 bg-white/10 backdrop-blur-md rounded-full shadow-inner ring-1 ring-white/20">
                <Cpu size={36} className="text-emerald-400 animate-pulse" />
             </div>
             <div>
                 <h3 className="text-xs font-black uppercase tracking-widest text-emerald-400 mb-2 flex items-center gap-2"><Zap size={14}/> AI Profile Insight</h3>
                 <p className="text-white text-lg font-medium leading-relaxed max-w-4xl">{aiSuggestion}</p>
             </div>
        </div>

        {history.length > 0 ? (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Historical Log */}
                <div className="bg-white dark:bg-gray-800 p-10 rounded-[2.5rem] shadow-2xl border border-gray-100 dark:border-gray-700">
                    <h2 className="text-2xl font-black mb-8 text-[var(--color-forest-canopy)] dark:text-white flex items-center gap-3">
                        <TrendingUp className="text-[var(--color-terracotta)]" /> Your Footprint History
                    </h2>
                    <div className="h-80 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                        <AreaChart data={history} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                        <defs>
                            <linearGradient id="colorCO2" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#10b981" stopOpacity={0.3}/>
                            <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                            </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" opacity={0.5} />
                        <XAxis dataKey="name" stroke="#94a3b8" axisLine={false} tickLine={false} dy={10} tick={{ fontSize: 12, fontWeight: 'bold' }} />
                        <YAxis stroke="#94a3b8" axisLine={false} tickLine={false} dx={-10} tick={{ fontSize: 12, fontWeight: 'bold' }} />
                        <Tooltip contentStyle={{ borderRadius: '1rem', border: 'none', boxShadow: '0 20px 40px rgba(0,0,0,0.1)', fontWeight: 'bold' }} />
                        <Area type="monotone" dataKey="CO2" name="CO₂ (kg)" stroke="#10b981" strokeWidth={4} fillOpacity={1} fill="url(#colorCO2)" />
                        </AreaChart>
                    </ResponsiveContainer>
                    </div>
                </div>

                {/* AI Predictive Graph */}
                <div className="bg-white dark:bg-gray-800 p-10 rounded-[2.5rem] shadow-2xl border border-gray-100 dark:border-gray-700 relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-32 h-32 bg-red-500/5 rounded-full filter blur-[50px] pointer-events-none"></div>
                    <h2 className="text-2xl font-black mb-8 text-[var(--color-forest-canopy)] dark:text-white flex items-center gap-3 relative z-10">
                        <Cpu className="text-blue-500" /> AI Predictive Trajectory (2030)
                    </h2>
                    <div className="h-80 w-full relative z-10">
                    <ResponsiveContainer width="100%" height="100%">
                        <AreaChart data={predictiveData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" opacity={0.5} />
                        <XAxis dataKey="year" stroke="#94a3b8" axisLine={false} tickLine={false} dy={10} tick={{ fontSize: 12, fontWeight: 'bold' }} />
                        <YAxis stroke="#94a3b8" axisLine={false} tickLine={false} dx={-10} tick={{ fontSize: 12, fontWeight: 'bold' }} />
                        <Tooltip contentStyle={{ borderRadius: '1rem', border: 'none', boxShadow: '0 20px 40px rgba(0,0,0,0.1)', fontWeight: 'bold' }} />
                        <Area type="monotone" dataKey="Current Trajectory" stroke="#ef4444" strokeWidth={3} fill="none" dot={{ r: 4 }} />
                        <Area type="monotone" dataKey="Sustainable Goal" stroke="#3b82f6" strokeWidth={3} fill="none" dot={{ r: 4 }} />
                        </AreaChart>
                    </ResponsiveContainer>
                    </div>
                </div>
            </div>
        ) : (
          <div className="text-center py-20 bg-white dark:bg-gray-800 rounded-[3rem] border border-gray-100 dark:border-gray-700 shadow-xl max-w-3xl mx-auto">
            <Footprints className="mx-auto text-emerald-500/50 w-20 h-20 mb-6" />
            <h3 className="text-3xl font-black text-gray-800 dark:text-white mb-4">No Baseline Established</h3>
            <p className="text-lg text-gray-500 dark:text-gray-400 mb-8 font-medium">Head to the calculator to establish your footprint so our AI can generate projections.</p>
            <motion.button 
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => navigate('/calculator')} 
              className="bg-[var(--color-forest-canopy)] dark:bg-emerald-500 text-white px-10 py-5 rounded-2xl font-black uppercase tracking-widest shadow-2xl hover:shadow-emerald-500/50 transition-all hover:bg-[var(--color-terracotta)] dark:hover:bg-emerald-400"
            >
              Initialize Calculator
            </motion.button>
          </div>
        )}
      </div>
    </div>
  );
};

export default Dashboard;
